### ISSUE TITLE
I cannot call `init` if the directory is not empty

### ISSUE THREAD

**Issue by somenxavier** [claudiodangelis/banco#7]
Just this
```
[xan@coronari pro]$ ls
banco
[xan@coronari pro]$ ./banco init
2021/04/07 23:26:26 directory /home/xan/tmp/pro is not empty
```

It seems like something absurd

**Comment by claudiodangelis** [comment]
hello @somenxavier, it is not absurd, if you want to initialize a project the directory must be empty, because `banco` needs to create directories and does not want to take responsibility of choosing what to do in case a directory already exists.
